# This workflow will build, sign, and package a WinUI 3 MSIX desktop application
# built on .NET.

name: WinUI 3 MSIX app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    env:
      solution-name: FUSapp.sln
      msix-project-path: FUSapp/FUSapp.wapproj
      package-name: FUSapp
      configuration: Release
      vm-image: windows-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore ${{ env.solution-name }}

    - name: Build solution
      run: msbuild ${{ env.solution-name }} /p:Configuration=${{ env.configuration }} /p:Platform=x64 /m

    - name: Create MSIX package
      run: msbuild ${{ env.msix-project-path }} /p:Configuration=${{ env.configuration }} /p:Platform=x64 /p:UapAppxPackageBuildMode=StoreUpload

    - name: Upload MSIX package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.package-name }}
        path: |
          **/${{ env.package-name }}*.msixbundle
          **/${{ env.package-name }}*.msixupload
